fields:
  - &fieldDataKey
    label: Data Key
    name: dataKey
    widget: hidden

  - &fieldTemplateKey
    label: Template Key
    name: templateKey
    widget: hidden

  - &fieldTitle
    label: HTML Title
    name: title
    widget: string
    required: true

  - &fieldDescription
    label: HTML Description
    name: description
    widget: text
    required: true

  - &fieldBody
    label: Body
    name: body
    widget: markdown
    required: true
    buttons:
      - bold
      - italic
      - link
      - heading-one
      - heading-two
      - heading-three
      - bulleted-list
      - numbered-list
    editor_components:
      - image

backend:
  name: git-gateway
  branch: master

local_backend: true

site_url: https://crossfitamgruen.netlify.app

media_folder: static/img
public_folder: /img

collections:
  - name: pagesMain
    label: Main pages
    description: List of most relevant pages like the homepage, schedule or contact page.
    files:
      - file: src/pages/index.md
        preview_path: /
        name: index
        label: Homepage
        fields:
          - *fieldTemplateKey
          - *fieldTitle
          - *fieldDescription

          - label: Slider
            label_singular: Slider item
            name: slider
            widget: list
            summary: "{{fields.text}}"
            min: 2
            fields:
              - label: Text
                name: text
                widget: string
                required: true
              - label: Image
                name: image
                widget: image
                required: true

          - label: Info boxes
            label_singular: Info box
            name: infoBoxes
            widget: list
            summary: "{{fields.text}}"
            min: 2
            fields:
              - label: Text
                name: text
                widget: text
                required: true
              - label: Image
                name: image
                widget: image
                required: true

      - file: src/pages/stundenplan.md
        preview_path: /stundenplan
        label: Schedule
        name: schedule
        fields:
          - *fieldTemplateKey
          - *fieldTitle
          - *fieldDescription
          - *fieldBody
          - label: Eversports widget ID
            name: eversportsId
            widget: string
            required: true

      - file: src/pages/kontakt.md
        preview_path: /kontakt
        label: Contact
        name: contact
        fields:
          - *fieldTemplateKey
          - *fieldTitle
          - *fieldDescription
          - <<: *fieldBody
            editor_components:
              - contactForm
              - image

      - file: src/pages/kontakt/erfolgreich.md
        preview_path: /kontakt/erfolgreich
        label: Contact form success page
        name: contactSuccess
        fields:
          - *fieldTemplateKey
          - *fieldTitle
          - *fieldDescription
          - *fieldBody


  - name: pagesLowPrio
    label: Legal pages and others
    description: List of less relevant pages like the disclosure, imprint or not found pages.
    files:
      - file: src/pages/datenschutz.md
        preview_path: /datenschutz
        label: Disclosure
        name: disclosure
        fields:
          - *fieldTemplateKey
          - *fieldTitle
          - *fieldDescription
          - *fieldBody

      - file: src/pages/impressum.md
        preview_path: /impressum
        label: Imprint
        name: imprint
        fields:
          - *fieldTemplateKey
          - *fieldTitle
          - *fieldDescription
          - *fieldBody

      - file: src/pages/404.md
        preview_path: /404
        label: Not found page
        name: notFound
        fields:
          - *fieldTemplateKey
          - *fieldTitle
          - *fieldDescription
          - *fieldBody


  - name: layout
    label: General layout settings
    description: Configure general settings and layout components.
    files:
      - file: src/data/header.yml
        label: Header
        name: header
        fields:
          - *fieldDataKey
          - label: Header text main
            name: headerMain
            widget: string
            required: true
          - label: Header text small
            name: headerSmall
            widget: string
            required: true

      - file: src/data/footer.yml
        label: Footer
        name: footer
        fields:
          - *fieldDataKey
          - label: Footer link columns
            label_singular: Footer link column
            name: linkColumns
            widget: list
            summary: Column
            min: 1
            max: 3
            collapsed: false
            fields:
              - label: Footer links
                label_singular: Footer link
                name: links
                widget: list
                summary: "{{fields.text}} ({{fields.link}})"
                min: 1
                fields:
                  - label: Text
                    name: text
                    widget: string
                    required: true
                  - label: Link
                    name: link
                    widget: string
                    required: true
