fields:
  - &fieldTemplateKey
    label: Template Key
    name: templateKey
    widget: hidden

  - &fieldTitle
    label: HTML Title
    name: title
    widget: string

  - &fieldDescription
    label: HTML Description
    name: description
    widget: text

  - &fieldBody
    label: Body
    name: body
    widget: markdown
    buttons:
      - bold
      - italic
      - link
      - heading-one
      - heading-two
      - heading-three
      - bulleted-list
      - numbered-list
    editor_components:
      - image

backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: pages
    label: Pages
    files:
      - file: src/pages/index.md
        label: Landing Page
        name: index
        fields:
          - *fieldTemplateKey
          - *fieldTitle
          - *fieldDescription

          - label: Slider
            label_singular: Slider item
            name: slider
            widget: list
            summary: "{{fields.text}}"
            min: 2
            fields:
              - label: Text
                name: text
                widget: string
              - label: Image
                name: image
                widget: image

          - label: Info boxes
            label_singular: Info box
            name: infoBoxes
            widget: list
            summary: "{{fields.text}}"
            min: 2
            fields:
              - label: Text
                name: text
                widget: text
              - label: Image
                name: image
                widget: image

      - file: src/pages/datenschutz.md
        label: Disclosure
        name: disclosure
        fields:
          - *fieldTemplateKey
          - *fieldTitle
          - *fieldDescription
          - *fieldBody

      - file: src/pages/impressum.md
        label: Imprint
        name: imprint
        fields:
          - *fieldTemplateKey
          - *fieldTitle
          - *fieldDescription
          - *fieldBody

      - file: src/pages/kontakt.md
        label: Contact
        name: contact
        fields:
          - *fieldTemplateKey
          - *fieldTitle
          - *fieldDescription
          - *fieldBody

      - file: src/pages/kontakt/erfolg.md
        label: Contact Success
        name: contactSuccess
        fields:
          - *fieldTemplateKey
          - *fieldTitle
          - *fieldDescription
          - *fieldBody
